In [2]:
import pandas as pd

### metacademy

In [5]:
# Load the dataset
data = pd.read_csv('../data/metacademy/metacademy-prerequisite-pairs-transoformed-to-wikipedia.csv')
print(data.info())
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3201 entries, 0 to 3200
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   prereq_wiki_canonical_title   3201 non-null   object
 1   MA_preq                       3201 non-null   object
 2   MA_concept                    3201 non-null   object
 3   concept_wiki_canonical_title  3201 non-null   object
dtypes: object(4)
memory usage: 100.2+ KB
None

,prereq_wiki_canonical_title,MA_preq,MA_concept,concept_wiki_canonical_title
0,Set (mathematics),countable sets,cardinality,Cardinality
1,Set (mathematics),countable sets,cardinality,Infinity
2,Set (mathematics),countable sets,completeness of first-order logic,First-order logic
3,Set (mathematics),countable sets,completeness of first-order logic,G�del's completeness theorem
4,Set (mathematics),countable sets,compactness of propositional logic,Compactness theorem

In [ ]:
"""

걱정되는 점
1. prereq_wiki_canonical_title이 우리가 생각하는 category 느낌보다 domain, field, topic 느낌이 강함
   -> 이렇다면 따로 노드를 만들어야 하나? 아니면 그냥 큰 KC로 둬야 하나? category를 삭제해야 할 수도.. 필요도 없고 category 정의가 애매
2. 깃허브 데이터셋은 원래 이렇게 쓸만한 게 없나? 다 폴더로 나뉘어져있고 concept을 우리가 다 합쳐야 함.. 
   -> 만약 그렇다면 지금 논문 페이지에서 가져온 이 데이터셋을 가지고 구축해야 할 듯
   -> wiki 링크도 수집 필요함

"""

### tutorialbank

In [15]:
# Load the dataset
edge_data = pd.read_csv('../data/tutorialbank/prerequisite_annotations.csv')
kc_data = pd.read_csv('../data/tutorialbank/prerequisite_topics.csv')
print(kc_data.info())
kc_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   topic_id         208 non-null    int64
 1    topic_name      208 non-null    object
 2    wikipedia_link  184 non-null    object
dtypes: int64(1), object(2)
memory usage: 5.0+ KB
None

,topic_id,topic_name,wikipedia_link
0,2,Anaphora Resolution,https://en.wikipedia.org/wiki/Anaphora_(lingui...
1,3,Generative Adversarial Networks,https://en.wikipedia.org/wiki/Generative_adver...
2,4,Neural Machine Translation,https://en.wikipedia.org/wiki/Neural_machine_t...
3,5,Variational Autoencoders,https://en.wikipedia.org/wiki/Autoencoder#Vari...
4,6,IBM Translation Models,https://en.wikipedia.org/wiki/IBM_alignment_mo...

In [16]:
print(edge_data.info())
edge_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42643 entries, 0 to 42642
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   source_topic_id   42643 non-null  int64
 1    target_topic_id  42643 non-null  int64
 2    prereq_relation  42643 non-null  int64
 3   annotator_id      42643 non-null  int64
dtypes: int64(4)
memory usage: 1.3 MB
None

   source_topic_id   target_topic_id   prereq_relation  annotator_id
0                2                 3                -1            56
1                2                 4                -1             3
2                2                 5                -1             3
3                2                 6                -1             3
4                2                 7                -1            15

In [19]:
edge_data.columns

Index(['source_topic_id', ' target_topic_id', ' prereq_relation',
       'annotator_id'],
      dtype='object')

In [21]:
edge_data[edge_data[" prereq_relation"] == 1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 904 entries, 34 to 42221
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   source_topic_id   904 non-null    int64
 1    target_topic_id  904 non-null    int64
 2    prereq_relation  904 non-null    int64
 3   annotator_id      904 non-null    int64
dtypes: int64(4)
memory usage: 35.3 KB

In [ ]:
"""
걱정되는 점
1. kc_data에 있는 204번째 줄이 이상
   205,Information Theory: coding, compression, mutual information,NULL,NULL
   -> 그냥 내가 손수 데이터를 수정 
   -> 205,"Information Theory: coding, compression, mutual information",NULL
2. kc_data에 칼럼며이 없어서 그냥 직접 넣어줌
   -> topic_id, topic_name , wikipedia_link
3. KC 206개, 엣지 904개
"""